apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: masodatc/nodejs-app:01
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 3000 #this is the external port
      targetPort: 3000 #this port must be the same with container port