apiVersion: v1
kind: Service
metadata:
  name: rest-node-app-svc-mongodb
  labels:
    app: restnodejs
spec:
  ports:
    - port: 27017
  selector:
    app: restnodejs
    tier: mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-node-mongodb
  labels:
    app: restnodejs
spec:
  selector:
    matchLabels:
      app: restnodejs
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: restnodejs
        tier: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        env:
        - name: MYDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-pass
              key: password
        ports:
        - containerPort: 27017
          name: mongodb