apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-node-js-app
  labels:
    app: restnodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restnodejs
  template:
    metadata:
      labels:
        app: restnodejs
    spec:
      containers:
      - name: restnodejs
        image: masodatc/rest-api-nodejs:01
        env:
        - name: MONGODB_CONNSTRING
          value: mongodb://${mongoAuth}mongodb-service:${mongoPort}/${mongoDb}?authSource=admin
          #value: 'mongodb://node-app-user:mypass2@mongodb-service:27017/mydatabase?authSource=admin'  
        - name: RESTNODE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-pass
              key: username
        - name: RESTNODE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-pass
              key: password
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rest-node-app-svc
spec:
  type: NodePort
  selector:
    app: restnodejs
  ports:
    - port: 3000 #this is the external port
      targetPort: 3000 #this port must be the same with container port

